---
abstract: 'Perl extension for converting Pod to old-style Pod.'
author:
  - 'Robin Barker <rmbarker@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Plainer
no_index:
  directory:
    - t
    - inc
requires:
  Pod::Parser: '0'
  perl: '5.006000'
version: '1.04'
